### ISSUE TITLE
Unable to convert .NET Framework 4.8 Test Project

### ISSUE THREAD

**Issue by tomaustin700** [dotnet/try-convert#156]
Hi,
I am trying to convert a .NET Framework 4.8 Test project but I am getting the following error:
``` 
Not all project type guids are supported.
All supported project type guids:
        fae04ec0-301f-11d3-bf4b-00c04f79efbc
        60dc8134-eba5-43b8-bcc9-bb4bc16c2548
All given project type guids:
        {3AC096D0-A1C2-E12C-1390-A8335801FDAB}
        {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}
```

It seems that #70 added the functionality to convert test projects, should ```3AC096D0-A1C2-E12C-1390-A8335801FDAB``` have been added to https://github.com/dotnet/try-convert/blob/a53657754e1c9e9b3cde79b7580234d6133ff44c/src/MSBuild.Conversion.Facts/DesktopFacts.cs#L52 ?

Hope you can help!
Tom

**Comment by jmarolf** [comment]
@tomaustin700 could you point to a sample project this is happening on? It will make this much easier to fix.

**Comment by tomaustin700** [comment]
Hi @jmarolf
I have uploaded a sample project here: https://github.com/tomaustin700/TestConvertIssue

Hope this helps.
