### ISSUE TITLE
Enabling Nullable Reference Types

### ISSUE THREAD

**Issue by dotnokato** [dotnet/try-convert#271]
Hello,
Is there a plan to enable Nullable Reference Types for try-convert projects?
If yes, I am happy to work on a pull request for that.

**Comment by jmarolf** [comment]
I started the work for that here: https://github.com/dotnet/format/pull/627

**Comment by cartermp** [comment]
@dotnokato I think NRT would be great to add. Happy to review any PRs you want to contribute.

**Comment by dotnokato** [comment]
@cartermp please review and let me know if anything needs changing

**Comment by jmarolf** [comment]
closed by #272
