### ISSUE TITLE
Install error: Failed to retrieve information about 'try-convert'

### ISSUE THREAD

**Issue by Edgaras91** [dotnet/try-convert#277]
Fails to install, trying to get nuget package not from nuget reposatory.

See below error in bold, I have renamed private nuget source with "*not Nuget*".
In nuget.config at AppData\Roaming\NuGet top row of `<packageSources>` is  
`<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />`

C:\WINDOWS\system32>dotnet tool install -g try-convert

**C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : Failed to retrieve information about 'try-convert' from remote source 'https://packages.*not Nuget*/FindPackagesById()?id='try-convert'&semVerLevel=2.0.0'. [C:\Users\name\AppData\Local\Temp\lofrauwi.lfq\restore.csproj]**
C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error :   Response status code does not indicate success: 500 (Internal Server Error). [C:\Users\name\AppData\Local\Temp\lofrauwi.lfq\restore.csproj]
The tool package could not be restored.
Tool 'try-convert' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by cartermp** [comment]
@Edgaras91 I don't think this has to do with `try-convert` itself. What happens if you run the install command with `--add-source` at the command-line?

**Comment by Edgaras91** [comment]
> 
> 
> @Edgaras91 I don't think this has to do with `try-convert` itself. What happens if you run the install command with `--add-source` at the command-line?

I don't know how to use this argument, so I used it like this and that didn't work:
`dotnet tool install -g try-convert --add-source https://api.nuget.org/v3/index.json`

**Comment by cartermp** [comment]
You may need to add your additional source within quotes.

Though it's worth noting that this is not really related to `try-convert`. This is a general global tools thing you're running into, and since `try-convert` is a global tool you're seeing it. I recommend filing an issue here if you can't get it to work: github.com/dotnet/sdk
