### ISSUE TITLE
Print all the expected and unexpected imports when a project is rejected due to custom imports

### ISSUE THREAD

**Issue by cartermp** [dotnet/try-convert#295]
If I have a project with a packages.config dependency that added some custom imports, the tool will fail since we don't really know what these do. Often the best course of action is to just delete these imports. The tool should print all of the imports it finds and doesn't recognize to the screen.

Additionally, we should print out the imports we expected to be there.

**Comment by p2635** [comment]
Any updates on this? I used this tool for the first time but I have no idea what to do to progress through this error. I tried to strip any lines that have the word 'import' in the csproject file but it still hits a wall.

**Comment by cartermp** [comment]
@p2635 we accept pull requests, the code to do handle this should be pretty easy to find when placed under a debugger.
