### ISSUE TITLE
how to install without internet connection

### ISSUE THREAD

**Issue by hemantbhai100** [dotnet/try-convert#299]
i have dotnet sdk 3.1

i do not have access to internet to install via command line in the corporate network.

dotnet install command tries to download the entire sdk all over again.

how can i install this program without the command line accessing the internet.

**Comment by cartermp** [comment]
@hemantbhai100 this tool does require an internet connection. It is a global tool, which means it comes from the NuGet gallery. You can download the binaries from the [Releases](https://github.com/dotnet/try-convert/releases) page and install them locally from a flash drive or build this tool from source. If you install locally, this is the command you'll need to use:

```
dotnet tool install -g try-convert --version 0.2.105701 --add-source \\Path\To\Folder\With\The\Package
```
