### ISSUE TITLE
How to install a preview version of try-convert?

### ISSUE THREAD

**Issue by MaherJendoubi** [dotnet/try-convert#315]
![image](https://user-images.githubusercontent.com/1798510/95897088-3d01a580-0d8d-11eb-82b4-f10828521899.png)

**Comment by MaherJendoubi** [comment]
cc @cartermp

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/95898300-21979a00-0d8f-11eb-9139-8c1d0cd3b661.png)

**Comment by jmarolf** [comment]
This command succeeds for me:

```bash
dotnet tool install --global try-convert --version 0.6.151301
```

perhaps nuget is taking its time percolating updates.

**Comment by cartermp** [comment]
Yeah this seems like a point-in-time issue. The latest update is on nuget.

**Comment by MaherJendoubi** [comment]
Thanks a lot @jmarolf & @cartermp !
