### ISSUE TITLE
Can't build if .net 5 installed already as 5.0.100-rc.1.20452.10 fails to install

### ISSUE THREAD

**Issue by rjk** [dotnet/try-convert#323]
When I run build.cmd it fails with 

```
C:\code\sandbox\try-convert>build.cmd
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20452.10/dotnet-sdk-5.0.100-rc.1.20452.10-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20452.10/dotnet-sdk-5.0.100-rc.1.20452.10-win-x64.zip
Failed to install dotnet from public location.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20452.10/dotnet-sdk-5.0.100-rc.1.20452.10-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rc.1.20452.10/dotnet-sdk-5.0.100-rc.1.20452.10-win-x64.zip
Failed to install dotnet from public location.

```
If I try to install that SDK manually from https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.100-rc.1-windows-x64-installer it fails and the log file says 

`[68A8:24B8][2020-11-13T14:04:41]e000: Error 0x80070666: Cannot install a product when a newer version is installed.
`

I guess this is because I've got the .net 5.0 released version installed already?

fwiw, I'm trying to build from master because building from PR 318 fails for me with 

`C:\code\sandbox\try-convert\src\MSBuild.Conversion.Package\PackagesConfigParser.cs(95,47): error CS8602: Dereference of a possibly null reference. [C:\code\sandbox\try-convert\src\MSBuild.Conversion.Package\MSBuild.Conversion.Package.csproj]
`

but since other people think the PR is fine I guessed the error was environmental. So I tried building from master, and got the errors as above :'(

Using the released binary I hit issue #317, building from PR 318 gives me a build error and building from master gives me an SDK install error.

**Comment by cartermp** [comment]
This should be resolved now with latest master.
