### ISSUE TITLE
try-convert fails with Microsoft.Build.Exceptions.InvalidProjectFileException, can't find Microsoft.WebApplication.targets

### ISSUE THREAD

**Issue by rjk** [dotnet/try-convert#337]
With version 0.7.157502, running `try-convert -w mysolution.sln --force-web-conversion --no-backup` gave me this error: 

```
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files\dotnet\sdk\5.0.100\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.100\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.  C:\PATH\TO\MY\PROJECT.csproj
```

Indeed that file is not there. Within `C:\Program Files\dotnet\sdk\5.0.100\Microsoft` I have just `Microsoft.NET.Build.Extensions` folder. 

My project builds fine in VS2019. In the csproj file I see these lines: 

```
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
  <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v10.0\WebApplications\Microsoft.WebApplication.targets" Condition="false" />
```

Based on [this suggestion](https://stackoverflow.com/a/44064473/8479) I installed a couple more components in VS and retried but to no avail. I have all the relevant web & build bits I could find. 

What do I need to install, or is it something wrong with my .csproj file? 

Thanks for any help.

**Comment by johanbenschop** [comment]
I got the same error. It looks to me like it's looking in the wrong place for the target files. I've copied the contents of `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio`  into `C:\Program Files\dotnet\sdk\5.0.100\Microsoft\VisualStudio` where afterwards the error disappeared.

**Comment by rjk** [comment]
Thanks! I did the same and it worked, but in my case copying from `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio` since I'm on Community edition.

**Comment by cartermp** [comment]
Okay, I figured out what the error is. It's the same as https://github.com/dotnet/try-convert/issues/305 - the issue is that the MSBuild loaded by try-convert is not the same as the MSBuild loaded by Visual Studio. The latter knows what to do with that the we import declarations. The .NET SDK MSBuild that the tool uses does not. A fix will be to just remove those altogether, since they're going to be implicit anyways.
