### ISSUE TITLE
A WPF project should be converted using the "Microsoft.NET.Sdk.WindowsDesktop" sdk instead of "Microsoft.NET.Sdk"

### ISSUE THREAD

**Issue by Rand-Random** [dotnet/try-convert#343]
The title basically says it all.

Tested this with a new wpf .net framework project and it converted it to this

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>
```

It seems I was missing this when I tried to multi target the wpf project
https://github.com/dotnet/wpf/issues/3865

**Comment by cartermp** [comment]
We explicitly don't do this when targeting .NET 5 because that SDK is an artifact of .NET Core 3.1 days. If it's needed for multi-targeting then that is likely just a bug.
