### ISSUE TITLE
Error unsupported TypeScript imports

### ISSUE THREAD

**Issue by johanbenschop** [dotnet/try-convert#347]
When running try-convert on a web project I get the error that the project has custom imports that are not accepted by it.

> Unexpected custom imports were found:
>         Microsoft.TypeScript.Default.props
>         Microsoft.TypeScript.targets

These imports are a leftover from a time where the project contained typescript files, but those are long gone.  Manually removing the two imports from the csproj resolved the error. Maybe try-convert should remove and/or ignore these imports?

**Comment by cartermp** [comment]
Hmmm, I don't think we can guarantee that these imports won't be necessary in the converted project. This is why we're strict with imports in general. Only ones that we know will be irrelevant are accounted for.
