### ISSUE TITLE
Exclude legacy web projects

### ISSUE THREAD

**Issue by cartermp** [dotnet/try-convert#35]

**Comment by hareshambaliya** [comment]
Why legacy web project is filtered out?

**Comment by hareshambaliya** [comment]
I am getting the <ProjectName> is a legacy web project, which is unsupported by this tool. I looked at the code and found the following.

`// Reject if it's a web project
                else if (root.PropertyGroups.Any(pg => pg.Properties.Any(ProjectPropertyHelpers.IsLegacyWebProjectTypeGuidsProperty)))
                {
                    Console.WriteLine($"'{root.FullPath}' is a legacy web project, which is unsupported by this tool.");
                    return false;
                }`

I think this as an enhancement.

**Comment by cartermp** [comment]
@hareshambaliya The tool won't support legacy web projects because they require a full-scale rewrite to ASP.NET Core to work on .NET Core. Nearly every API is completely different, the tools are different, and the capabilities are different. To avoid leading people on into thinking that they can reasonably convert a project, the tool simply rejects them.

**Comment by hareshambaliya** [comment]
@cartermp Isn't there possible to convert the project with the report of failed items?
