### ISSUE TITLE
Project Reference Aliases are not preserved

### ISSUE THREAD

**Issue by icnocop** [dotnet/try-convert#361]
Hi.

When converting a project that has a reference to another project and uses an `Alias`, the `Aliases` element is not preserved.

For example, before try-convert:
```
    <ProjectReference Include="..\ProjectB\ProjectB.csproj">
      <Project>{e8b261af-d233-4260-baf8-7446ece92154}</Project>
      <Name>ProjectB</Name>
      <Aliases>ProjectBAlias</Aliases>
    </ProjectReference>
```
After try-convert:
```
    <ProjectReference Include="..\ProjectB\ProjectB.csproj" />
```

Therefore, statements like `extern alias ProjectBAlias;` and `ProjectBAlias::Class1` will fail to compile.
Also, compiler errors like `CS0433: The type Class1 exists in both ProjectB and ProjectC.` may appear.

To work-around this issue, I have to manually add back the `Aliases` element:
```
    <ProjectReference Include="..\ProjectB\ProjectB.csproj">
      <Aliases>ProjectBAlias</Aliases>
    </ProjectReference>
```

**Comment by cartermp** [comment]
Thanks for the report! This should be relatively easy to fix. The code that removes metadata from the items is here:

https://github.com/dotnet/try-convert/blob/b657e5d12d353475ab32492de9e4c8d287f23df8/src/MSBuild.Conversion.Project/ProjectRootElementExtensionsForConversion.cs#L156-L162

Could just filter out items that aren't an `Aliases` and it should likely do the trick. Would you be interested in submitting a PR?
