### ISSUE TITLE
Allow enabling support for custom imports

### ISSUE THREAD

**Issue by mjrousos** [dotnet/try-convert#370]
Currently, try-convert doesn't work with projects that import unrecognized targets and props. This makes sense for a conservative migration approach, but prevents the tool from being useful on a lot of customer projects that import targets files specific to their organization or from reference NuGet packages.

It would be really useful to have an opt-in way of having try-convert work with projects using unrecognized props and targets files. I'm not sure whether the better behavior would be to remove those imports or leave them (I *think* leaving them or perhaps leaving them commented out would be best), but somehow being able to run try-convert on such projects would be valuable.

**Comment by rmaloo** [comment]
+1 we too are having similar issue using try-convert tool

**Comment by mjrousos** [comment]
I'm working on a fix for this.
