### ISSUE TITLE
Exception converting project 'Sequence contains more than one element'

### ISSUE THREAD

**Issue by ejohnson-dotnet** [dotnet/try-convert#388]
Trying to convert any project I am getting the following exception:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains more than one element
  Source=System.Linq
  StackTrace:
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at MSBuild.Conversion.SDK.TargetFrameworkHelper.FindHighestInstalledTargetFramework(Boolean usePreviewSDK) in 
C:\try-convert\src\MSBuild.Conversion.SDK\TargetFrameworkHelper.cs:line 60
```

Line 60 in TargetFrameworkHelper.cs is:
```
var templateNugetPackagePath = Directory.EnumerateFiles(templatePath, "microsoft.dotnet.common.projecttemplates.*.nupkg", SearchOption.TopDirectoryOnly).Single();
```

Debugging this, the variable `templatePath = "C:\\Program Files\\dotnet\\templates\\5.0.4"`
If I look in that folder I find these two matching files:
`microsoft.dotnet.common.projecttemplates.5.0.5.0.4.nupkg`
`microsoft.dotnet.common.projecttemplates.5.0.5.0.200-preview.21109.7.nupkg`

I have not installed any .NET Core preview releases or anything like that, only official released packages.

**Comment by cartermp** [comment]
This tool doesn't install any templates, so you must have acquired that somewhere else. I will track this as a bug though, since we should probably be resilient to this. Happy to look at a PR as well.
