### ISSUE TITLE
Installation doesn't work, error local source

### ISSUE THREAD

**Issue by vhanla** [dotnet/try-convert#80]
I downloaded nupkg file from releases page and wrote the command to install, 
`dotnet tool install -g try-convert --version 0.1.50202 --add-source F:\Projects\C#\try-convert.0.1.50202.nupkg`
but error occurs:

```
C:\Program Files\dotnet\sdk\3.0.100\NuGet.targets(123,5): 
error : Local source "F:\Projects\C#\try-convert.0.1.50202.nupkg" 
doesn't exist. [C:\Users\username\AppData\Local\Temp\lenwl3hq.4vq\restore.csproj]
```
Why is that?

**Comment by HSchwichtenberg** [comment]
Just a guess: try to store the package in a different path without "#".

**Comment by jmarolf** [comment]
@vhanla if you specify the folder and not the file path the installation will succeed

```
dotnet tool install -g try-convert --version 0.1.50202 --add-source F:\Projects\C#
```

**Comment by jmarolf** [comment]
@vhanla 	please re-open this if this did not fix your issue
