### ISSUE TITLE
For WinForm projects AssemblyInfo and Forms are duplicated

### ISSUE THREAD

**Issue by paul1956** [dotnet/try-convert#88]
AssemblyInfo because it is autogenerated by DotNet and exists under My Project directory. Forms and their dependencies are autogenerated and are left in vbproj file.

**Comment by jmarolf** [comment]
This is intentional. We add the `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>` attribute so you are not opted into generating assembly infos. Is this not what you are seeing?

**Comment by paul1956** [comment]
No I don't see GenerateAssemblyInfo, I get an error that there a duplicate AssemblyInfo items until I deleted AssemblyInfo.VB.

**Comment by jmarolf** [comment]
That sounds like a bug. Can you point me at a project where this reproduces? I do not see this happening on newly created .NET 4.8 Winforms projects that are converted to core

**Comment by paul1956** [comment]
It is not OpenSource but I tried again from a clean backup and the GenerateAssemblyInfo false is in the project file but the files already exist so I get the error. I will close the issues in not the converter.
