### ISSUE TITLE
UseWindowsForms true property is missing

### ISSUE THREAD

**Issue by paul1956** [dotnet/try-convert#89]
\<UseWindowsForms>true\</UseWindowsForms> is missing and the line below needs to be added to all forms and .Designer files (maybe because something is missing from project file.
```
Imports System.Windows.Forms
```

**Comment by jmarolf** [comment]
`<UseWindowsForms>true</UseWindowsForms>` should be there. Can you give me an example project where that is not the case?

We don't handle default imports for vb project files, but I wouldn't expect us to remove them.

**Comment by paul1956** [comment]
By default Winforms Framework projects don't require the imports System.Windows.Forms but after convertion I need to add it to the Form.vb and Designer.vb file. UseWindowsForms is something new in Core 3.0 so no you don't remove it but I also didn't see it added.

**Comment by jmarolf** [comment]
> UseWindowsForms is something new in Core 3.0 so no you don't remove it but I also didn't see it added.

That sounds like a bug. Can you get me a project this reproduces on?

**Comment by paul1956** [comment]
Again not open source but again the issue is not the missing line but the missing reference to System.Windows.Forms so I will close with "As Designed". I could open another to add a reference to "System.Windows.Forms" to the project.
